Fed_Interest_Rate:
  code_name: "FEDFUNDS"
  source: fred
  calc: raw
  freq: monthly
  start_year: 2024
  start_month: 2
  unit: "%"
  description: "Federal Funds Effective Rate"

M2_Supply:
  code_name: "M2SL"
  source: fred
  calc: raw
  freq: monthly
  start_year: 2024
  start_month: 3
  unit: Billion
  description: "M2 Money Stock, Billions of Dollars"
